name: CI

on:
  push:
    branches: dev

jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build the Docker image
        run: docker build -t listener:v1 .
      -
        name: Tag the Docker image
        run: docker tag listener:v1 agbusko/listener
      -
        name: Push the Docker image to the registry
        run: docker push agbusko/listener